### PR TITLE
Create my-journey-SergiuGeorgePop-149936133.md

### PR DESCRIPTION
**Pull request by SeGePop**
feature: added personal journey.md

### CODE REVIEW

**Comment by dan-marius** [comment]
Te rog redenumeste fisierul conform task-ului 4. Apoi pot merge-ui si pull req. tau.

**Comment by SeGePop** [comment]
> Te rog redenumeste fisierul conform task-ului 4. Apoi pot merge-ui si pull req. tau.

Cum trebuie redenumit?

"In the Journey folder, create your journey file with the next template: my-journey-YourName-YourGITHUBId.md"
my-journey-SergiuGeorgePop(YourName)-149936133(YourGITHUBId).md

**Comment by SeGePop** [comment]
Done

**Comment by dan-marius** [comment]
Welcome!

**Pull request merged**
